chore: coin98 wallet add signMessage method
near/wallet-selector pull request #1122
Opened 2024-06-26 10:34 UTC by khiemsoft

Thanks for taking the time to submit a pull request!

If you haven't already, be sure to take a look at the [CONTRIBUTING](https://github.com/near/wallet-selector/blob/main/CONTRIBUTING.md) documentation to get up to speed with the practices in this repository.

When you're ready, switch to the "Preview" tab to select an applicable template:

- [General template (most common)](?expand=1&template=general.md)
- [Wallet integration template](?expand=1&template=wallet_integration.md)

2024-07-15 21:56 UTC, trechriron commented
Please make a template selection above, fill in the details, and mark the appropriate checkboxes. Thanks!

2024-07-15 22:17 UTC, trechriron requested changes
1. Please find and copy the correct template for your initial comment. You may have to resubmit. Please close this one if you do. You MUST have the checkboxes present or tests will not pass.
2. Always make your initial PR against the DEV branch.

After these are fixed, we can review your changes. Thanks!

2024-07-16 21:00 UTC, trechriron commented
@khiemsoft  - did you see my request for changes?

2024-07-26 08:43 UTC, khiemsoft commented
> @khiemsoft - did you see my request for changes?

Hi, I just fixed this warning. Please verify it. Thanks for your support.

2025-01-28 18:37 UTC, gagdiez approved these changes

2025-02-06 15:47 UTC, trechriron approved these changes
Good

2025-02-06 15:52 UTC, merged