docs(react): fix react sample startup guide & add needful dependency …
near/wallet-selector pull request #1128
Opened 2024-07-03 14:21 UTC by AlienegraGeek

# Description

Refined the guidance for example and added a required dependency that otherwise would have prevented the sample service from starting due to dependency and build issues.

# Checklist:

- [√] I have performed a self-review of my own code
- [√] I have commented my code, particularly in hard-to-understand areas
- [√] I have made corresponding changes to the documentation
- [√] My changes generate no new warnings

# Type of change.

- [ ] FIX - a PR of this type patches a bug.
- [ ] FEATURE - a PR of this type introduces a new feature.
- [ ] BUILD - a PR of this type introduces build changes.
- [ ] CI - a PR of this type introduces CI changes.
- [√] DOCS - a PR of this type introduces DOCS improvement.
- [ ] STYLE - a PR of this type introduces style changes.
- [ ] REFACTOR - a PR of this type introduces refactoring.
- [ ] PERFORMANCE - a PR of this type introduces performance changes.
- [ ] TEST - a PR of this type adds more tests.
- [ ] CHORE - a PR introduces other changes than the specified above.

2024-07-15 22:14 UTC, trechriron requested changes
Please change the initial branch merge to DEV. Thanks!

2024-07-16 08:06 UTC, AlienegraGeek commented
> Please change the initial branch merge to DEV. Thanks!

done

2024-07-16 20:52 UTC, trechriron submitted a review, later dismissed

2024-07-17 06:14 UTC, pivanov requested changes

2024-07-17 06:14 UTC, pivanov commented on examples/react/README.md
> +yarn build all
I think this line should be:
```
yarn build:all
```

2024-07-17 06:14 UTC, pivanov commented on package.json
> +    "@near-wallet-selector/modal-ui": "^8.9.10",
I think we don't need to add @near-wallet-selector/modal-ui as dependency because of NX.

2024-07-19 07:24 UTC, pivanov submitted a review, later dismissed
nice :)
r+

2024-07-19 07:46 UTC, frol commented
@AlienegraGeek Sorry for jumping in, but I'd like to invite you to participate in the [Race of Sloths](https://race-of-sloths.com) - a fun and gamified open-source contributions program. Consider mentioning @race-of-sloths user in your github comment or PR description to join!

See how the flow works here: https://github.com/near/nearcore/pull/11778

2024-07-19 09:36 UTC, AlienegraGeek commented
@race-of-sloths

2024-07-19 09:37 UTC, race-of-sloths commented
@AlienegraGeek Thank you for your contribution! Your pull request is now a part of the [Race of Sloths](https://race-of-sloths.com)!
New Sloth joined the Race! Welcome!

[<picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://badge.race-of-sloths.com/AlienegraGeek?type=bot&theme=dark">
    <source media="(prefers-color-scheme: light)" srcset="https://badge.race-of-sloths.com/AlienegraGeek?type=bot&theme=light">
    <img alt="Shows profile picture for the author of the PR" src="https://badge.race-of-sloths.com/AlienegraGeek?type=bot&theme=white">
</picture>](https://race-of-sloths.com/profile/AlienegraGeek)


<details><summary>Current status: <i>waiting for scoring</i></summary>

We're waiting for maintainer to score this pull request with `@race-of-sloths score [0,1,2,3,5,8,13]` command
</details><details><summary>What is the Race of Sloths</summary>
<p>
Race of Sloths is a friendly competition where you can participate in challenges and compete with other open-source contributors within your normal workflow

For contributors:

- Tag @race-of-sloths inside your pull requests
- Wait for the maintainer to review and score your pull request
- Check out your position in the [Leaderboard](https://race-of-sloths.com/leaderboard)
- Keep weekly and monthly streaks to reach higher positions
- Boast your contributions with a dynamic picture of your [Profile](https://race-of-sloths.com/profile/AlienegraGeek)

For maintainers:
- Score pull requests that participate in the Race of Sloths
- Engage contributors with fair scoring and fast responses so they keep their streaks
- Promote the Race to the point where the Race starts promoting you
- Grow the community of your contributors

Feel free to check [our website](https://race-of-sloths.com) for additional details!
</p>
</details> 

<details>
<summary>Bot commands</summary>

- For contributors
  - **Include a PR:** `@race-of-sloths include` to enter the Race with your PR
- For maintainers:
  - **Assign points:** `@race-of-sloths score [1/2/3/5/8/13]` to award points based on your assessment.
  - **Reject this PR:** `@race-of-sloths exclude` to send this PR back to the drawing board.
  - **Exclude repo:** `@race-of-sloths pause` to stop bot activity in this repo until `@race-of-sloths unpause` command is called

</details>

2024-08-02 05:57 UTC, pivanov submitted a review, later dismissed
r+

2024-08-17 06:14 UTC, race-of-sloths commented
### ❌ PR inactive
This PR has been inactive for two weeks. It's now marked as stale. 
>[!TIP]
If you think it's a mistake, you can restart the bot with `include` command to proceed 🔄

2025-02-06 15:46 UTC, gagdiez approved these changes

2025-02-06 15:46 UTC, trechriron submitted a review, later dismissed
LGTM

2025-02-06 15:52 UTC, gagdiez submitted a review, later dismissed

2025-02-06 15:59 UTC, gagdiez submitted a review, later dismissed

2025-02-06 16:01 UTC, trechriron submitted a review, later dismissed

2025-02-06 16:03 UTC, merged