safePal
near/wallet-selector pull request #394
Opened 2022-08-13 03:31 UTC by bryanForSafe

# Description

Added safePal wallet login entry

Closes # (issue)

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

# Type of change. This type of change is the main reason for the PR.

- [ ] FIX - a PR of this type patches a bug.
- [ ] FEATURE - a PR of this type introduces a new feature.
- [ ] BUILD - a PR of this type introduces build changes.
- [ ] CI - a PR of this type introduces CI changes.
- [ ] DOCS - a PR of this type introduces DOCS improvement.
- [ ] STYLE - a PR of this type introduces style changes.
- [ ] REFACTOR - a PR of this type introduces refactoring.
- [ ] PERFORMANCE - a PR of this type introduces performance changes.
- [ ] TEST - a PR of this type adds more tests.
- [ ] CHORE - a PR introduces other changes than the specified above.

# Breaking changes

- [ ] BREAKING CHANGE - SPECIFY: _______
- [ ] NO BREAKING CHANGE - this PR doesn't contain any breaking changes and it's backwards compatible

2022-08-16 15:32 UTC, AmmarHumackicSQA commented
Hi @bryanForSafe , thanks for submitting this PR. You can find the criteria for including new wallets for Wallet Selector in our [CONTRIBUTING.md](https://github.com/near/wallet-selector/blob/main/CONTRIBUTING.md#listing-third-party-wallet-on-wallet-selector) file, and please confirm that the criteria are met or can be met within the required timeline.

2022-08-19 09:08 UTC, bryanForSafe commented
OK, thank you, we'll get it done.

2022-08-19 09:08 UTC, bryanForSafe commented
> Hi @bryanForSafe , thanks for submitting this PR. You can find the criteria for including new wallets for Wallet Selector in our [CONTRIBUTING.md](https://github.com/near/wallet-selector/blob/main/CONTRIBUTING.md#listing-third-party-wallet-on-wallet-selector) file, and please confirm that the criteria are met or can be met within the required timeline.

OK, thank you, we'll done it.

2022-09-09 13:41 UTC, HarisSQA approved these changes

2022-09-14 08:25 UTC, HarisSQA commented on packages/safePal/src/lib/safePal.ts
> +  return waitFor(() => !!window.safePalNear?.isSafePal).catch(() => false);
Need to use safepal variable instead of safePalNear

2022-09-14 08:26 UTC, HarisSQA commented on packages/safePal/src/lib/safePal.ts
> +    if (!_state.wallet.isSignedIn()) {
Need to use isConnected boolean instead of isSingedIn()

2022-09-14 08:29 UTC, HarisSQA commented on packages/safePal/src/lib/safePal.ts
> +    const accountId = _state.wallet.getAccountId();
Function getAccount() instead of getAccountId()

2022-09-14 08:49 UTC, kujtimprenkuSQA reviewed
Could you please rename the package to lowercase `safepal` or split it into 2 words `safe-pal` because the naming does not align with other packages which we already have?

Please update your branch to match the latest changes of our `dev` branch and fix the conflicts.

2022-09-15 06:19 UTC, HarisSQA requested changes
There is many things that need to be changed and it should update to the latest version. There is nearly 300 commits difference. Also need to change the function in files and clean it up!

2022-09-29 11:16 UTC, AmmarHumackicSQA commented
Hi @bryanForSafe when can we expect these changes to be implemented? Thanks.

2022-10-11 13:52 UTC, AmmarHumackicSQA commented
> Hi @bryanForSafe when can we expect these changes to be implemented? Thanks.

@bryanForSafe can you provide any info on this? Thanks!

2022-11-28 07:30 UTC, AmmarHumackicSQA commented
@bryanForSafe gentle bump 🙂

2022-12-15 09:46 UTC, DamirSQA commented
Hey @bryanForSafe , any news on this one?

2023-01-05 14:38 UTC, AmmarHumackicSQA commented
Hey, @bryanForSafe can you let us know what is the status regarding this PR? We might need to close it soon if we don't get any response. Thanks

2023-01-10 19:29 UTC, closed without merging