feat: Initial implementation of importAccountsByEncryptedUrl on MNW and Meteor Wallet
near/wallet-selector pull request #570
Opened 2022-11-22 06:04 UTC by hcho112

# Description

This PR contains initial implementation for adding `importAccountsByEncryptedUrl` interface for `My Near Wallet` and `Meteor Wallet`. [WEP-211](https://pagodaplatform.atlassian.net/browse/WEP-211) 

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

# Type of change.

- [ ] FIX - a PR of this type patches a bug.
- [ ] FEATURE - a PR of this type introduces a new feature.
- [ ] BUILD - a PR of this type introduces build changes.
- [ ] CI - a PR of this type introduces CI changes.
- [ ] DOCS - a PR of this type introduces DOCS improvement.
- [ ] STYLE - a PR of this type introduces style changes.
- [ ] REFACTOR - a PR of this type introduces refactoring.
- [ ] PERFORMANCE - a PR of this type introduces performance changes.
- [ ] TEST - a PR of this type adds more tests.
- [ ] CHORE - a PR introduces other changes than the specified above.

2022-11-22 22:29 UTC, andy-haynes commented
@hcho112 you beat me to the punch 😅 

Would you mind reviewing #575 and rebasing this on top once you're satisfied please? I'll update the document to reflect the changes I've made there

2022-12-01 22:41 UTC, hcho112 commented
@andy-haynes I have commented Meteor wallet's `buildImportAccountsUrl` until we know for sure the wallet type of the Meteor Wallet is `BrowserWallet` type.

2022-12-02 18:48 UTC, andy-haynes requested changes

2022-12-02 18:48 UTC, andy-haynes commented on packages/my-near-wallet/src/lib/my-near-wallet.spec.ts
> +    expect(wallet.buildImportAccountsUrl).toBeDefined();
Could we expect that this is a function instead please?

2022-12-02 18:48 UTC, andy-haynes commented on packages/my-near-wallet/src/lib/my-near-wallet.spec.ts
> +    );
Let's simplify this to just
```js
expect(wallet.buildImportAccountsUrl()).toEqual('https://testnet.mynearwallet.com/batch-import');
```

2022-12-02 18:48 UTC, andy-haynes commented on packages/meteor-wallet/src/lib/meteor-wallet.spec.ts
> +/* eslint-disable @nrwl/nx/enforce-module-boundaries */
Let's just shelve this until we have Meteor sorted out. No value in adding an empty test at the moment

2022-12-02 18:48 UTC, andy-haynes commented on packages/meteor-wallet/src/lib/meteor-wallet.ts
> +
Same as above, let's shelve until we have resolution on Meteor

2022-12-05 18:37 UTC, andy-haynes approved these changes

2022-12-05 19:17 UTC, merged