Dev
near/wallet-selector pull request #650
Opened 2023-01-17 17:20 UTC by prih

# Description

Add support of [FiNER Wallet](https://finerwallet.io) which can be installed from [App Store](https://apps.apple.com/us/app/finer-wallet/id1623425017) and [Chrome Store](https://chrome.google.com/webstore/detail/finer-wallet/mbboloafhcopdfokibemggdnhcocggpl)

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2023-01-18 10:48 UTC, prih commented
@AmmarHumackicSQA @amirsaran3 We reviewed all the nuances of interaction with the wallet on the mobile device, also added integration with the browser expansion

2023-01-18 11:31 UTC, AmmarHumackicSQA commented
> @AmmarHumackicSQA @amirsaran3 We reviewed all the nuances of interaction with the wallet on the mobile device, also added integration with the browser expansion

Thanks @prih, we will be checking it today.

2023-01-18 13:50 UTC, DamirSQA commented
Hi @prih , thanks for submitting this PR. 
I've noticed some issues that you might want to check out. 

On desktop view, the Finer wallet isn't visible in the list in case it's not installed. It should be present with the install page when selected. You can have a look at the example below. 

![image](https://user-images.githubusercontent.com/111346686/213183147-7b113a8c-cad0-4b62-a19a-f447465dbcdb.png)

In mobile view it is visible, but it throws this error when clicked.
![image](https://user-images.githubusercontent.com/111346686/213186928-1e696289-c0c5-4b4b-844d-a324d0d79cb0.png)

After installing extension, when I'm trying to use wallet I'm getting "user reject" error when clicked on next. 
You can check out [video example](https://www.loom.com/share/110ab09be45c44b98505d6bdf7d103b4)

2023-01-18 14:40 UTC, prih commented
> On desktop view, the Finer wallet isn't visible in the list in case it's not installed. It should be present with the install page when selected. You can have a look at the example below.

- fixed

2023-01-18 14:43 UTC, prih commented
> After installing extension, when I'm trying to use wallet I'm getting "user reject" error when clicked on next.

its in process, we are waiting for the renewal of expansion in the store... v0.1.4 - will open the extension window and inform the user about the need to connect the expansion with the mobile application.

2023-01-18 14:47 UTC, prih commented
> In mobile view it is visible, but it throws this error when clicked.

this message is not at the JS code level, when trying to open a mobile application using the URL scheme finer://
simulation on the desktop browser (devtools) does not make it a real mobile browser)

2023-01-18 16:25 UTC, prih commented
> > In mobile view it is visible, but it throws this error when clicked.
> 
> this message is not at the JS code level, when trying to open a mobile application using the URL scheme finer:// simulation on the desktop browser (devtools) does not make it a real mobile browser)

![image](https://user-images.githubusercontent.com/3285877/213235058-e50fbc37-0d60-4586-9425-bcc1149423d3.png)

2023-01-19 09:01 UTC, DamirSQA requested changes

2023-01-19 11:27 UTC, kujtimprenkuSQA commented
@prih this is my initial review. these are some of the issues:

- Your wallet (FiNER extension) is creating or overriding the existing `window.near` object which is conflicting with the `Sender` wallet.
- The code about communicating with the extension is confusing and `Sender` is mentioned in a  lot of places it's a bit misleading.
- `signAndSendTransaction` with a deposit is not working on the mobile wallet.

This PR is trying to combine 2 different wallet implementations for this reason we will need to decide if there is a need to split these into 2 different packages (wallets) like FiNER Wallet (mobile), FiNER Wallet(extension).

Could you have a look at the contributing docs too and make sure the FiNER wallet aligns with the criteria?
https://github.com/near/wallet-selector/blob/main/CONTRIBUTING.md#listing-criteria-for-third-party-wallet-on-wallet-selector

For the Extension can you see if it aligns with the NEP standard: https://github.com/near/NEPs/pull/408

2023-01-19 11:43 UTC, prih commented
> * Your wallet (FiNER extension) is creating or overriding the existing `window.near` object which is conflicting with the `Sender` wallet.

no, extension doesn't overwrite window.near only if it's undefined
<img width="491" alt="image" src="https://user-images.githubusercontent.com/3285877/213433456-9904d692-a668-492c-b702-3e257a6f54dd.png">

packages/finer-wallet uses window.finer.near directly...

2023-01-19 11:45 UTC, prih commented
> > * Your wallet (FiNER extension) is creating or overriding the existing `window.near` object which is conflicting with the `Sender` wallet.
> 
> no, extension doesn't overwrite window.near only if it's undefined <img alt="image" width="491" src="https://user-images.githubusercontent.com/3285877/213433456-9904d692-a668-492c-b702-3e257a6f54dd.png">
> 
> packages/finer-wallet uses window.finer.near directly...

<img width="718" alt="image" src="https://user-images.githubusercontent.com/3285877/213434189-5e7821f7-3303-4efd-bb67-bc741c5ca42f.png">

2023-01-19 11:46 UTC, kujtimprenkuSQA commented
> no, extension doesn't overwrite window.near only if it's undefined

One way to find out this strange behaviour is if you disable `Sender` in the extensions of your browser and try clicking the `Sender` option. Sender and Finer must be 2 separate things.

2023-01-19 11:47 UTC, prih commented
> * `signAndSendTransaction` with a deposit is not working on the mobile wallet.

yes, we see the problem, it worked before)

2023-01-19 12:30 UTC, prih commented on packages/finer-wallet/package.json
> +}
fixed

2023-01-19 12:31 UTC, prih commented on packages/finer-wallet/src/lib/finer-sender.ts
> +      near: InjectedFinerSender | undefined;
fixed

2023-01-19 12:31 UTC, prih commented on packages/finer-wallet/src/lib/finer-sender.ts
> +export interface SenderParams {
fixed

2023-01-19 12:32 UTC, prih commented on packages/finer-wallet/src/lib/finer-sender.ts
> +  // const cleanup = () => {
fixed

2023-01-19 12:32 UTC, prih commented on packages/finer-wallet/src/lib/finer-sender.ts
> +      logger.log("Sender:verifyOwner", { message });
fixed

2023-01-19 12:32 UTC, prih commented on packages/finer-wallet/src/lib/finer-sender.ts
> +      init: Sender,
fixed

2023-01-19 12:32 UTC, prih commented on packages/finer-wallet/src/lib/finer-sender.ts
> +
fixed

2023-01-19 12:32 UTC, prih commented on packages/finer-wallet/src/lib/injected-wallet.ts
> +interface SenderEvents {
fixed

2023-01-19 12:33 UTC, prih commented on packages/finer-wallet/src/lib/injected-wallet.ts
> +export interface InjectedFinerSender {
fixed

2023-01-19 12:45 UTC, prih commented
> > no, extension doesn't overwrite window.near only if it's undefined
> 
> One way to find out this strange behaviour is if you disable `Sender` in the extensions of your browser and try clicking the `Sender` option. Sender and Finer must be 2 separate things.

Yes, I understand, but what's the problem? are we prohibited from using this API? if the user install Sender Wallet, then it will work without problems...
this is implemented for projects that have not integrated wallet-selector and will not do it, but already have integration with browser-wallet and Sender (since they appeared before wallet-selector became mainstream), and are de facto standards, like for example in Ethereum world (and other EVM) MetaMask plays such a role with its window.ethereum provider, and no one is surprised by this fact that the user has the wallet that suits him, and not something with which he can connect to a specific dApp.

2023-01-19 12:50 UTC, prih commented
> This PR is trying to combine 2 different wallet implementations for this reason we will need to decide if there is a need to split these into 2 different packages (wallets) like FiNER Wallet (mobile), FiNER Wallet(extension).

why should we do this? our extension is not a standalone wallet, but a gateway for interacting with a mobile application, user can use the desktop experience, while his keys are safe on the mobile device

2023-01-19 12:53 UTC, prih commented
> For the Extension can you see if it aligns with the NEP standard: [near/NEPs#408](https://github.com/near/NEPs/pull/408)

yes, we are following this, when we make our implementation of the injected wallet for NEAR, we will definitely pay attention to these documents with recommendations, but at the moment I think this is not relevant, because. communication takes place via the wallet-selector interface

2023-01-19 13:07 UTC, kujtimprenkuSQA commented
> > > no, extension doesn't overwrite window.near only if it's undefined
> > 
> > 
> > One way to find out this strange behaviour is if you disable `Sender` in the extensions of your browser and try clicking the `Sender` option. Sender and Finer must be 2 separate things.
> 
> Yes, I understand, but what's the problem? are we prohibited from using this API? if the user install Sender Wallet, then it will work without problems... this is implemented for projects that have not integrated wallet-selector and will not do it, but already have integration with browser-wallet and Sender (since they appeared before wallet-selector became mainstream), and are de facto standards, like for example in Ethereum world (and other EVM) MetaMask plays such a role with its window.ethereum provider, and no one is surprised by this fact that the user has the wallet that suits him, and not something with which he can connect to a specific dApp.

If sender is not installed and you click it in the wallet selector UI it should show the `WalletNotInstalled` view and not prompt the connection with FiNER.

Based on the specification here Sender will eventually have to move to `window.near.sender` if they want to align with the Standard: https://github.com/near/NEPs/blob/master/specs/Standards/Wallets/InjectedWallets.md#specification

2023-01-19 13:16 UTC, kujtimprenkuSQA commented
> > This PR is trying to combine 2 different wallet implementations for this reason we will need to decide if there is a need to split these into 2 different packages (wallets) like FiNER Wallet (mobile), FiNER Wallet(extension).
> 
> why should we do this? our extension is not a standalone wallet, but a gateway for interacting with a mobile application, user can use the desktop experience, while his keys are safe on the mobile device

I see at first I thought the extension was a wallet too.

2023-01-19 13:22 UTC, prih commented
> If sender is not installed and you click it in the wallet selector UI it should show the `WalletNotInstalled` view and not prompt the connection with FiNER.
> 
> Based on the specification here Sender will eventually have to move to `window.near.sender` if they want to align with the Standard: https://github.com/near/NEPs/blob/master/specs/Standards/Wallets/InjectedWallets.md#specification

2023-01-19 13:25 UTC, prih commented
> If sender is not installed and you click it in the wallet selector UI it should show the `WalletNotInstalled` view and not prompt the connection with FiNER.

I agree, but this is done for compatibility, we can solve this by notifying the user that this is not a Sender and offering to use FiNER, if he refuses, then we will set a flag about this and will not offer FiNER, ok?

2023-01-19 13:27 UTC, prih commented
> Based on the specification here Sender will eventually have to move to `window.near.sender` if they want to align with the Standard: https://github.com/near/NEPs/blob/master/specs/Standards/Wallets/InjectedWallets.md#specification

ok, it's up to them, we just want users to be able to replace window.near if the dApp can only do that...

2023-01-19 18:56 UTC, prih commented
> * `signAndSendTransaction` with a deposit is not working on the mobile wallet.

it is interesting that it didn’t problem with us, the wallet is waiting for the finalization of the transaction, and it doesn’t happen in any way. node loses recipes... but in fact it is in the blockchain, just rpc for some reason does not associate it with this transaction...

example:
https://explorer.testnet.near.org/transactions/2z8WphkMiSXoz3tNrw6ehhWghbdSAVWB9JRwsJNSzv4p

we have made adjustments to our finalization check mechanism, it should work with the new app update...

2023-01-23 10:30 UTC, DamirSQA commented
Hi @prih , thanks for the changes and updates. `signAndSendTransaction` is working now, one thing left to be addressed is the `windows.near` issue.

2023-01-24 09:44 UTC, prih commented
> Hi @prih , thanks for the changes and updates. `signAndSendTransaction` is working now, one thing left to be addressed is the `windows.near` issue.

@DamirSQA @kujtimprenkuSQA 

what is the issue?) we do not see any problems and reasons to change anything, our extension is api compatible with Sender Wallet, and this is so for compatibility, there are dApps that have directly integrated this api, and do not use wallet-selector, or early versions of it.

ok, if you are not satisfied with how our extension works, then - what rules does he break?

2023-01-24 09:54 UTC, prih commented
Is this the decentralization we deserve? why are we dictated how we should make a wallet and what api should it have? are we somehow conflicting with sender-wallet ? - no, only if it is not installed by the user, we are trying to make life easier for the user.

2023-01-24 11:39 UTC, prih commented
> Hi @prih, the reason behind enforcing the standard is that we ensure everyone has the same conditions for their wallets without negative impact on each other.

what negative impact do we have? if the user has Sender installed, then our extension does not interfere with him in any way...

2023-01-24 12:06 UTC, AmmarHumackicSQA commented
> > If sender is not installed and you click it in the wallet selector UI it should show the `WalletNotInstalled` view and not prompt the connection with FiNER.
> 
> I agree, but this is done for compatibility, we can solve this by notifying the user that this is not a Sender and offering to use FiNER, if he refuses, then we will set a flag about this and will not offer FiNER, ok?

Hi @prih, what if some other wallet team wants the users to be directed to their wallet in the same way? 

It doesn't seem fair in this example not to show to the users when they select Sender the`WalletNotInstalled` view first as we have it currently, with the option for them to be redirected to the store to install it.

2023-01-24 12:19 UTC, prih commented
> 

this is understandable and logical, but the user has already installed, for example, the Finer extension, for some reason he needed another wallet, that is, for some reason he consciously wants to use both at once? ok, only in this case it ? when our extension is not installed, we do not recommend Finer instead of Sender.

2023-01-24 13:10 UTC, andrunovak commented
@AmmarHumackicSQA 

> Hi @prih, the reason behind enforcing the standard is that we ensure everyone has the same conditions for their wallets without negative impact on each other.

Please link this standard so we can find more details there.

2023-01-24 13:21 UTC, Olexiy-pt commented
@AmmarHumackicSQA 
> > > If sender is not installed and you click it in the wallet selector UI it should show the `WalletNotInstalled` view and not prompt the connection with FiNER.
> > 
> > 
> > I agree, but this is done for compatibility, we can solve this by notifying the user that this is not a Sender and offering to use FiNER, if he refuses, then we will set a flag about this and will not offer FiNER, ok?
> 
> Hi @prih, what if some other wallet team wants the users to be directed to their wallet in the same way?
> 
> It doesn't seem fair in this example not to show to the users when they select Sender the`WalletNotInstalled` view first as we have it currently, with the option for them to be redirected to the store to install it.


If the user didn't install Sender or Finer, where in the code do you find that we try to block Sender installation?

2023-01-24 13:33 UTC, AmmarHumackicSQA commented
> @AmmarHumackicSQA
> 
> > > > If sender is not installed and you click it in the wallet selector UI it should show the `WalletNotInstalled` view and not prompt the connection with FiNER.
> > > 
> > > 
> > > I agree, but this is done for compatibility, we can solve this by notifying the user that this is not a Sender and offering to use FiNER, if he refuses, then we will set a flag about this and will not offer FiNER, ok?
> > 
> > 
> > Hi @prih, what if some other wallet team wants the users to be directed to their wallet in the same way?
> > It doesn't seem fair in this example not to show to the users when they select Sender the`WalletNotInstalled` view first as we have it currently, with the option for them to be redirected to the store to install it.
> 
> If the user didn't install Sender or Finer, where in the code do you find that we try to block Sender installation?

Hi @Olexiy-pt it wasn't mentioned that you block it, but we are saying it should show the user how we currently have it with the`WalletNotInstalled` view. 

To show the option first for the users to be redirected to the store to install Sender if it's not installed already. You can check out our live example: [near.github.io/wallet-selector/](https://near.github.io/wallet-selector/). 

If you have some examples to share of your suggestions we would appreciate it. Thanks!

2023-01-24 14:10 UTC, prih commented
> > @AmmarHumackicSQA
> > > > > If sender is not installed and you click it in the wallet selector UI it should show the `WalletNotInstalled` view and not prompt the connection with FiNER.
> > > > 
> > > > 
> > > > I agree, but this is done for compatibility, we can solve this by notifying the user that this is not a Sender and offering to use FiNER, if he refuses, then we will set a flag about this and will not offer FiNER, ok?
> > > 
> > > 
> > > Hi @prih, what if some other wallet team wants the users to be directed to their wallet in the same way?
> > > It doesn't seem fair in this example not to show to the users when they select Sender the`WalletNotInstalled` view first as we have it currently, with the option for them to be redirected to the store to install it.
> > 
> > 
> > If the user didn't install Sender or Finer, where in the code do you find that we try to block Sender installation?
> 
> Hi @Olexiy-pt it wasn't mentioned that you block it, but we are saying it should show the user how we currently have it with the`WalletNotInstalled` view.
> 
> To show the option first for the users to be redirected to the store to install Sender if it's not installed already. You can check out our live example: [near.github.io/wallet-selector/](https://near.github.io/wallet-selector/).
> 
> If you have some examples to share of your suggestions we would appreciate it. Thanks!

well, we will remove the automatic set in window.near, and the user himself can enable it in the settings. @AmmarHumackicSQA - ok?

2023-01-24 14:36 UTC, AmmarHumackicSQA commented
> > > @AmmarHumackicSQA
> > > > > > If sender is not installed and you click it in the wallet selector UI it should show the `WalletNotInstalled` view and not prompt the connection with FiNER.
> > > > > 
> > > > > 
> > > > > I agree, but this is done for compatibility, we can solve this by notifying the user that this is not a Sender and offering to use FiNER, if he refuses, then we will set a flag about this and will not offer FiNER, ok?
> > > > 
> > > > 
> > > > Hi @prih, what if some other wallet team wants the users to be directed to their wallet in the same way?
> > > > It doesn't seem fair in this example not to show to the users when they select Sender the`WalletNotInstalled` view first as we have it currently, with the option for them to be redirected to the store to install it.
> > > 
> > > 
> > > If the user didn't install Sender or Finer, where in the code do you find that we try to block Sender installation?
> > 
> > 
> > Hi @Olexiy-pt it wasn't mentioned that you block it, but we are saying it should show the user how we currently have it with the`WalletNotInstalled` view.
> > To show the option first for the users to be redirected to the store to install Sender if it's not installed already. You can check out our live example: [near.github.io/wallet-selector/](https://near.github.io/wallet-selector/).
> > If you have some examples to share of your suggestions we would appreciate it. Thanks!
> 
> well, we will remove the automatic set in window.near, and the user himself can enable it in the settings. @AmmarHumackicSQA - ok?

Hi @prih that would be great. Thanks!

2023-01-30 12:08 UTC, prih commented
@AmmarHumackicSQA @DamirSQA we updated extension **v0.1.5**, it doesn't use `window.near` by default

2023-01-30 16:43 UTC, DamirSQA commented
Thanks @prih , I'll ask you to merge latest changes with your branch  before we proceed with merging PR.

2023-01-30 17:10 UTC, prih commented
> Thanks @prih , I'll ask you to merge latest changes with your branch before we proceed with merging PR.

done

2023-01-30 17:14 UTC, DamirSQA approved these changes

2023-01-30 17:38 UTC, merged

2023-01-30 17:39 UTC, prih commented
thx!

2023-04-11 10:06 UTC, AmmarHumackicSQA commented
Hi @prih we tried testing the latest version (v0.4.2) of the FiNER wallet and we are getting the "Something went wrong" msg while trying to set up the wallet (tried multiple options: quick start, create a new wallet, and import wallet). Here is the ss of what we are getting:

![IMG_0352](https://user-images.githubusercontent.com/95851006/231128132-8524ef86-98f1-4a82-8ba0-2754a397b978.PNG)

Can you take a look at this? Thanks!