feat: add account-export for WELLDONE
near/wallet-selector pull request #689
Opened 2023-02-06 10:31 UTC by Yoon-Suji

# Description

Add support for `buildImportAccountsUrl` in WELLDONE Wallet.
We also implemented the `importAccountsInSecureContext` method, but we decided to use the `buildImportAccountsUrl` for now because there is a little problem when calling the method without creating a wallet. If we solve the problem before the wallet-migration event starts, we plan to use the `importsAccountsInSecureContext` method.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# Type of change.

- [ ] FIX - a PR of this type patches a bug.
- [x] FEATURE - a PR of this type introduces a new feature.
- [ ] BUILD - a PR of this type introduces build changes.
- [ ] CI - a PR of this type introduces CI changes.
- [ ] DOCS - a PR of this type introduces DOCS improvement.
- [ ] STYLE - a PR of this type introduces style changes.
- [ ] REFACTOR - a PR of this type introduces refactoring.
- [ ] PERFORMANCE - a PR of this type introduces performance changes.
- [ ] TEST - a PR of this type adds more tests.
- [ ] CHORE - a PR introduces other changes than the specified above.

2023-02-07 00:48 UTC, hcho112 requested changes
Thank you for supporting the account export @Yoon-Suji 
Rest looks all good, but I would like to recommend to support either `buildImportAccountsUrl` or `importAccountsInSecureContext` but not both. 

For the sake of maintaining the codebase clean, we should aim to merge and push code if it is production ready. Refer to your description, currently `importAccountsInSecureContext` is not going to work right now, so ideally this part of implementation should be kept locally or in a seperate branch. 

When `importAccountsInSecureContext` is ready, I would recommend to create a PR that includes `importAccountsInSecureContext` and removes `buildImportAccountsUrl`.

2023-02-07 00:48 UTC, hcho112 commented on packages/welldone-wallet/src/lib/welldone.ts
> +    async importAccountsInSecureContext({ accounts }) {
Let's remove `importAccountsInSecureContext` on this PR if it is not ready from WELLDONE injected wallet side.

2023-02-07 00:48 UTC, hcho112 commented on packages/welldone-wallet/src/lib/welldone.ts
> +        useUrlAccountImport: true,
Let's remove `useUrlAccountImport` on this PR if it is not ready

2023-02-07 01:50 UTC, Yoon-Suji commented
Hi @hcho112 !
As you mentioned, I removed `importAccountsInSecureContext`, so WELLDONE Wallet only supports `buildImportAccountsUrl` method for now. I'll create a new PR when it is ready from the wallet side :)

2023-02-07 02:45 UTC, hcho112 commented on packages/welldone-wallet/src/lib/welldone.ts
> +        useUrlAccountImport: true,
my bad, we actually need this to be true in order to use `buildImportAccountsUrl` for injected wallet 😅

2023-02-07 02:56 UTC, hcho112 submitted a review, later dismissed
LGTM, I also ran the code locally and was able to export accounts successfully to WELLDONE wallet on testnet environment 👍

2023-02-09 02:16 UTC, Yoon-Suji commented
Hello @hcho112 ,
`importAccountsInSecureContext` is ready from the wallet and it's already been updated in Chrome Webstore! So I changed the method. Could you do the test again? Thank you :)

2023-02-09 04:32 UTC, hcho112 approved these changes
LGTM, `importAccountsInSecureContext` was working on local dev environment.

2023-02-09 04:32 UTC, merged