added translations for Croatian, Slovenian, Serbian, and Macedonian
near/wallet-selector pull request #734
Opened 2023-03-20 15:29 UTC by alenNBH

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

# Type of change.

- [ ] FIX - a PR of this type patches a bug.
- [ ] FEATURE - a PR of this type introduces a new feature.
- [ ] BUILD - a PR of this type introduces build changes.
- [ ] CI - a PR of this type introduces CI changes.
- [ ] DOCS - a PR of this type introduces DOCS improvement.
- [ ] STYLE - a PR of this type introduces style changes.
- [ ] REFACTOR - a PR of this type introduces refactoring.
- [ ] PERFORMANCE - a PR of this type introduces performance changes.
- [ ] TEST - a PR of this type adds more tests.
- [X] CHORE - a PR introduces other changes than the specified above.

2023-03-21 16:09 UTC, DamirSQA requested changes

2023-03-21 16:09 UTC, DamirSQA commented on packages/core/src/lib/locale/sl.json
> +        "hardware": "Potrdite povezavo s hladno denarnico"
"bridge": "Confirm the connection in the wallet" is missing

2023-03-21 16:09 UTC, DamirSQA commented on packages/core/src/lib/locale/mk.json
> +      "copyToClipboard": " Копирајте на клипборд",
Remove space in front of K

2023-03-31 09:23 UTC, alenNBH commented
Hi, I have added translations for the Export accounts sections and have resolved open changes. 
Let me know if there is anything left that needs to be fixed/resolved.

2023-03-31 12:28 UTC, DamirSQA requested changes

2023-03-31 12:28 UTC, DamirSQA commented on packages/core/src/lib/locale/sr.json
>        "enterYourPreferredHDPath": "Унесите жељену путању за ХД, а затим скенирајте све активне налоге.",
"enterYourPreferredHDPath": "Унесите жељену путању за ХД, а затим скенирајте све активне налоге." => 
"enterYourPreferredHDPath": "Унесите жељену жељену ХД путању, а затим скенирајте све активне налоге."

2023-03-31 12:28 UTC, DamirSQA commented on packages/core/src/lib/locale/hr.json
> +        "desc": "Bit će potrebno unijeti ovu lozinku na početku izvoza računa na drugi wallet.",
"desc": "Bit će potrebno unijeti ovu lozinku na početku izvoza računa na drugi wallet." => "desc": "Bit će potrebno unijeti ovu lozinku na početku izvoza naloga na drugi wallet."

2023-03-31 12:28 UTC, DamirSQA commented on packages/core/src/lib/locale/sr.json
> +        "noBalance": "Рачун није финансиран"
"noBalance": "Рачун није финансиран" => "noBalance": "Налог није финансиран"

2023-03-31 12:28 UTC, DamirSQA commented on packages/core/src/lib/locale/hr.json
> +        "noBalance": "Račun nema sredstava"
"noBalance": "Račun nema sredstava" => "noBalance": "Nalog nema sredstava"

2023-03-31 12:31 UTC, DamirSQA commented
> Hi, I have added translations for the Export accounts sections and have resolved open changes. Let me know if there is anything left that needs to be fixed/resolved.

Hi @alenNBH, and adding `"exportAccounts"`. and addressing required changes. I've added some comments, so if would be great if they could be addressed as well.

2023-04-03 12:34 UTC, DamirSQA approved these changes

2023-04-03 12:44 UTC, merged