Metamask snap
near/wallet-selector pull request #849
Opened 2023-07-18 00:35 UTC by AZbang

I'm from the HERE Wallet team, which received a grant to develop and maintain the official Metamask plugin. We are happy to present our work!

## How it works:
The wallet-selector package uses the @near-snap/sdk library which interacts with near-api-js and the metamask snap rpc.

The @near-snap/plugin itself does not have internet access. The plugin only signs transactions and provides an interface for viewing actions signed by the user.

## Plugin features:

### Limited access to a specific contract.
Method near_connect(contractId, network, methods) works in the same way as limited keys, that is, they allow you to send free transactions without annoying confirmations.

### Details of what the user is signing.
List of transaction actions, confirmations of new permissions, additional information. Unfortunately at the moment snap-ui is not very rich, but we are doing our best to make the UI/UX of the plugin better for the user.

### Support for delegated transactions. 
And own infrastructure for new users. HERE Wallet allows metamask users (on the mainnet) to send gas free transactions without having funds on their account.

### Free account activation in mainnet and testnet.
For users, the HERE Wallet metamask automatically activates accounts so that later it will be possible to use delegated transactions to interact with dApps without having funds on the account. (In the future, we hope to involve the NEAR Foundation in this, as we believe this is an important part of onboarding new users to the network)

### Long term support from our team.
We have been developing the NEAR infrastructure for a year now and are not going to stop. We are very excited to contribute to another important ecosystem service.

2023-07-18 15:35 UTC, DamirSQA commented
Greetings, after some initial testing it seems that it is working properly. 

Some issues were noticed with the Metamask Flask. Install button is blocked/disabled, so in order to go through this step, flex property needed to be disabled with inspector as a workaround. 

![no install](https://github.com/near/wallet-selector/assets/111346686/47bddb72-0f69-436d-9fb8-cac71f4acf77)
![remove install](https://github.com/near/wallet-selector/assets/111346686/3e3d0817-457c-4c45-a4d0-b477ce4bd70f)

Aside from that, Near token amount is not being displayed after funding and importing Near token.  

![image](https://github.com/near/wallet-selector/assets/111346686/0cce963c-fecf-45bf-945e-90921a68558c)

2023-07-19 13:09 UTC, DamirSQA commented
@AZbang , all good, comments added are mainly for the future reference.
In that regard, here is[ the recording of the flow](https://www.loom.com/share/8e3b9ea584004955aac55f2c0a15ad2c). (transaction confirmation popup is not showing on recording though)

We have some questions about the packages:

- What’s the reason behind adding an additional package, instead replacing Near Snap?

- Why is Metamask name being used instead of Near, and what is idea behind the old Near Snap package, to deprecate it or to replace it? "

2023-07-19 14:43 UTC, DamirSQA requested changes
Added some comments, also there are linting issues that should be addressed.

2023-07-19 14:43 UTC, DamirSQA commented on packages/metamask-snap/package.json
> +  "dependencies": {
Dependencies needs to be added only in the root level `package.json`, and it will be detected automatcaly, so it should be removed from here.

2023-07-19 14:43 UTC, DamirSQA commented on packages/metamask-snap/yarn.lock
Yarn lock inside metamask-snap needs to be removed.

2023-07-19 14:43 UTC, DamirSQA commented on examples/react/contexts/WalletSelectorContext.tsx
> +        setupMetamaskSnap({}),
It shouldn't be required for empty object to be present. You can have a look on other wallets/packages.

2023-07-22 09:29 UTC, AZbang commented
@DamirSQA  I didn't know if the previous metamask plugin could be removed. Did this!

2023-07-24 14:15 UTC, erditkurteshiSQA commented on README.md
> +  @near-wallet-selector/near-snap \
Can you please remove this import because it's already imported?

2023-07-24 14:15 UTC, erditkurteshiSQA commented on README.md
> +  @near-wallet-selector/near-snap \
Can you please remove this import because it's already imported?

2023-07-24 14:15 UTC, erditkurteshiSQA commented on examples/react/contexts/WalletSelectorContext.tsx
> +        setupNearSnap(),
Can you please remove this import because it's already added to the line above?

2023-07-24 14:15 UTC, erditkurteshiSQA commented on package.json
> +    "build:near-snap": "nx run-many --target=build --projects=near-snap --configuration=production",
Can you please remove this script, because it is duplicated?

2023-07-24 14:15 UTC, erditkurteshiSQA commented on packages/near-snap/README.md
> +This is the NEAR Metamask Snap package for NEAR Wallet Selector.
Can you please rename everything in this file to match with setupNearSnap?

2023-07-24 14:15 UTC, erditkurteshiSQA commented on packages/near-snap/project.json
> +  "tags": ["browser-wallet"]
Is there any particular reason why this is changed to browser-wallet?

2023-07-24 14:15 UTC, erditkurteshiSQA commented on packages/near-snap/tsconfig.json
> +    "module": "commonjs",
In the project.json we already define the format. This is not needed.

2023-07-24 14:15 UTC, erditkurteshiSQA commented on tsconfig.base.json
> +      ],
Can you please remove these lines, because they are duplicated?

2023-07-27 08:47 UTC, erditkurteshiSQA commented
Hi @AZbang ,

I left some comments regarding the last commit that needs to be addressed.
Also, these issues that are mentioned in this comment: https://github.com/near/wallet-selector/pull/849#issuecomment-1640464557 are still showing on some screens.

2023-08-08 22:05 UTC, AZbang commented
@erditkurteshiSQA  fixed all discussions! Also i added signMessage implementation

2023-08-08 22:55 UTC, AZbang commented
Also you can check mainnet guest-book demo 
https://near-snap.surge.sh/

2023-08-09 13:07 UTC, DamirSQA commented
Hi @AZbang it seems that Metamask(near) snap is not working properly after changes if not still work in progress, and Angular example seems to be broken, so it would be great if you can check that out as well.

2023-08-09 14:16 UTC, AZbang commented
@DamirSQA Can you find out more about what doesn't work? On the video, I check that everything works correctly:
https://www.veed.io/view/d7ff74f5-83ee-4d57-a0fb-7a38c6d64de3?sharingWidget=true&panel=share

The Angular example did indeed break, however this is not related to this PR because the problem is in the build system, I tried to fix it but I'm new to Angular and couldn't fix it quickly.

2023-08-09 15:01 UTC, DamirSQA commented
@AZbang it was the issue of wrong version in Metamask, after changing to v0.5.0 it worked properly.

2023-08-09 15:35 UTC, DamirSQA commented
@AZbang In order to fix Angular you can do the next:
- Install needed dependencies as devDependencies
`yarn add -D path-browserify`
`yarn add -D util`

- Update paths in `tsconfig.base.json` in wallet-selector (root) and add:
`"path": ["node_modules/path-browserify"]`

- This will now throw another error about the process version missing. 
To fix it update `polyfills.ts` in angular example add version to process:
`(window as any).process = { env: {}, version: "" };`

2023-08-10 11:00 UTC, DamirSQA commented on packages/near-snap/README.md
> +## Here Wallet JS SDK
Change Here Wallet to Near Snap

2023-08-10 11:00 UTC, DamirSQA commented on packages/near-snap/README.md
> +- `iconUrl`: (`string?`): Icon is optional. Default image point to Here Wallet Logo in base64 format.
Change Here Wallet to Near Snap

2023-08-10 11:04 UTC, DamirSQA commented
@AZbang  You can just do small changes in Readme, and we'll add Angular fix after merging.

2023-08-10 13:28 UTC, DamirSQA approved these changes

2023-08-10 13:29 UTC, merged